name: "Download Govulners"
author: "Nextlinux"
description: "Downloads the Govulners binary and provides a path to execute it"
branding:
  color: blue
  icon: check-circle
inputs:
  govulners-version:
    description: "A specific version of Govulners to install"
    required: false
  run:
    description: "Flag to indicate which sub-action to run"
    required: false
    default: "download-govulners"
outputs:
  cmd:
    description: "An absolute path to the Govulners executable"
runs:
  using: "node16"
  main: "../dist/index.js"
